# -*- coding: utf-8 -*-
"""Penguine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JvZwF-MbEjCHNktjSgtDebAzJpj1WdC9
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

penguins=pd.read_csv('penguins_cleaned.csv')

penguins_df=penguins.copy()

le=LabelEncoder()

penguins_df['island']=le.fit_transform(penguins_df['island'])
penguins_df['sex']=le.fit_transform(penguins_df['sex'])

y=penguins_df['species']
X=penguins_df.drop(['species'],axis=1)

penguins_df.head(10)

model=RandomForestClassifier()

model.fit(X,y)

import pickle

pickle.dump(model, open('penguins_classification.pkl','wb'))